# -*- coding: utf-8 -*-
"""
Created on Sun Jul 14 10:17:54 2019

@author: Cédric Perion | Arthur Dujardin

Contains reading and writing functions for ply files as well as a conversion function and other useful functions related to ply files
"""


import numpy as np
import plyfile

def readply(fname):
    """ Reads data from the ply file"""
    ply = open(fname, mode='rb')
    plydata = plyfile.PlyData.read(ply)
    return plydata

def writeply(data, fname):
    """
    Writes data to the plyfile
    @param data : the data to convert in ply
    @paramtype data : np.array
    @param fname : the name of the ply file
    @paramtype fname : string
    :return : ply data
    :rtype : plydata
    """
    el = plyfile.PlyElement.describe(data, 'vertex')
    plyfile.PlyData([el], text=True).write(fname)
    return data

def convertCoordinatesPlyArray(plydata):
    """
    Convert a plydata to a numpy array. The user can choose how many colors to add to each point (R, V, B)
    @plydata : the .ply element
    @plydatatype : plydata
    :return : the coordinates of every points from the cloud
    :rtype : np.array    
    """
    data = np.array([plydata.elements[0].data['x'], 
             plydata.elements[0].data['y'], 
             plydata.elements[0].data['z']])
    #print(len(plydata.elements[0].data['x']))
    #print(len(plydata.elements[0].data['y']))
    #print(len(plydata.elements[0].data['z']))

    return np.transpose(data)





def addchannelFromPly(plydata, coord, channel):
    """
    Add the channel to the numpy data (converted by the function convertCoordinatePlyArray)
    @plydata : the .ply element
    @plydatatype : plydata
    @coord : the data which contains the coordinates of every points
    @coordtype :np.array
    @channel : the name of the channel to add
    @channeltype : string
    :return : data + the colors to the coord data
    :rtype : np.array
    """
    #print(len(np.transpose(plydata.elements[0].data[channel])))
    data = np.column_stack((coord, plydata.elements[0].data[channel]))
    return data

def addchannelGenerated(data, channel_data, channel_names):
    """
    Add a channel (usually generated by a projection into other images) to the numpy data
    @data : the data which contains the coordinates of every points
    @datatype :np.array
    @channel_data : a list of every values of the channel
    @paramtype channel_data : np.array
    @channel_name : the name of the channel to add
    @channeltype : string
    :return : data + the colors to the coord data
    :rtype : np.array
    """
    if len(channel_data) != len(data):
        print("\nERROR : different size between the channel added and the matrix of coordinates points\n\n")
    else:
        coord = np.column_stack((data, channel_data))
    return coord



def convertPlyArray(plydata, channel = "all"):
    data = convertCoordinatesPlyArray(plydata)
    if channel.lower() == "all":
        data = addchannelFromPly(plydata, data, "red")
        data = addchannelFromPly(plydata, data, "green")
        data = addchannelFromPly(plydata, data, "blue")
        
    elif channel.lower() == "red":
        data = addchannelFromPly(plydata, data, "red")
        
    elif channel.lower() == "blue":
        data = addchannelFromPly(plydata, data, "blue")
        
    elif channel.lower() == "green":
        data = addchannelFromPly(plydata, data, "green")
        
    return data



if __name__ == "__main__" :
    fname = "NuageGREEN.ply"
    plydata = readply(fname)
    
    #1/ Converting the plydata to an array
    data = convertCoordinatesPlyArray(plydata)
    print("The data from the plydata is :\n", data)
    
    #2/ Adding channel
    channel = "green"
    data = addchannelFromPly(plydata, data, channel)
    print("\nAdding the channel ", channel, " to the data :\n", data)
    
    
    
    
    
    